#include "util.h"

// Variables

const char* invalInfoExt = "Extension not supported. Exiting...\n";

const char* invalDisplayExt = "Passed file is not a sprite file. Exiting...\n";

const int EC_invalExt = 0xBADF11E;

const char* validInfoExts[] = {
    "mhs",
    "bmp"
};

const char* validDisplayExts[] = {
    "mhs"
};

const int valIExtLen = sizeof(validInfoExts) / sizeof(validInfoExts[0]);

const int valDExtLen = sizeof(validDisplayExts) / sizeof(validDisplayExts[0]);

// Functions

void spewInfo(FILE* stream, char* extension){
    int extNum = stringWithinArray(extension, validInfoExts, valIExtLen);
    if(extNum == -1){
        errorOut(invalInfoExt, EC_invalExt);
    }
    switch(extNum){
        case(0):
            pSpr_t* spr = genSpriteObj(stream);
            displaySpriteData(spr);
            destroySpriteObj(spr);
            break;
        case(1):
            bmpRawFile_t* bmp = createRawBMP(stream);
            bmpDetailsOut(bmp);
            destroyRawBMP(bmp);
            break;
        default:
            errorOut(switchDef, EC_switchDef);
    }
}

void spriteDisplay(FILE* stream, char* extension){
    int extNum = stringWithinArray(extension, validDisplayExts, valDExtLen);
    if(extNum == -1){
        errorOut(invalDisplayExt, EC_invalExt);
    }
    switch(extNum){
        case(0):
            int palNum = 0;
            pSpr_t* spr = genSpriteObj(stream);
            printf("Please pick a number between 1 and %d\t-> ",\
                    spr->info->palCount);
            scanf("%d", &palNum);
            palNum--;
            spriteToConsole(spr, palNum);
            destroySpriteObj(spr);
            break;
        default:
            errorOut(switchDef, EC_switchDef);
            break;
    }
}

// Help Text Defines

#define INFO_HELP "\n\
\tHelp Text for: INFO\n\n\
\"info\" is used to view header information within supported file types.\n\n\
Supported file types are the following:\n\
\tMHS (MH Sprite): A sprite file generated by this program\n\
\tBMP (Bitmap): A Windows bitmap file.\n\n\
\tUSAGE: ./mhit info PATH_TO_FILE"

#define CONS_HELP "\n\
\tHelp Text for: CONS\n\n\
\"cons\" is used to draw a generated sprite to the console. This mode can\n\
be used to both quickly view a sprite and check the output from the\n\
\"convert\" mode, though it is limited by the size of your console.\n\n\
Supported file types are the following:\n\
\tMHS (MH Sprite): A sprite file generated by this program\n\n\
\tUSAGE: ./mhit cons PATH_TO_FILE\n"

#define CONVERT_HELP "\n\
\tHelp Text for: CONVERT\n\
\"convert\" is used to create a single MHS file from two specially formatted\n\
BMP files. The \"skeleton\" BMP is a 16-color greyscale image, while the\n\
\"palettes\" image is, at maximum, a 16x16 image, where each row is a palette\n\
in the final sprite. If you decide to save the data, the program will prompt\n\
you for a path relative to the current working directory.\n\n\
\tUSAGE: ./mhit convert PATH_TO_SKELETON PATH_TO_PALETTES\n"

#define HELP_TEXT_2 "\n\
Nice try, very funny; use \"help\" alone for what you're tying to do.\n"

#define VERSION_HELP "\n\
\tHelp Text for: VERSION\n\n\
\"version\" prints version information and exits.\n\n\
\"Version information\" includes the following values:\n\
Program Version,\n\
GCC version,\n\
Compile date and time\n\n\
\tUSAGE: ./mhit version\n"

#define VIS_TEST_HELP "\n\
\tHelp Text for: VIS-TEST\n\n\
\"vis-test\" is used to run one of five small tests for the SDL-based\n\
visualizer used by MHIT. It takes one argument out of the following:\n\n\
\t\"A\" - Displays a salmon-like color throughout the whole window\n\
\t\"B\" - Draws ramdomly-sized, ramdomly-colored boxes to the display window\n\
\t\"C\" - Draws randomly-colored lines with random starting and ending points\n\
\t\"D\" - Draws randomly colored pixels to the window\n\
\t\"E\" - Tests the built-in font Minif\n\n\
\tUSAGE: ./mhit vis-test TEST_LETTER\n"

#define DISPLAY_HELP "\n\
\tHelp Text for: DISPLAY\n\
\'display,\" obviously, displays a sprite. Compared to \"cons,\" which uses\n\
ANSI and a compatable console, \"display\" uses SDL2 and opens a slightly\n\
interactive window. The controls for the window are as follows:\n\
\t\"q\" - Quit displaying sprite and exit program\n\
\t\"4\" - Shift sprite left by one unit\n\
\t\"6\" - Shift sprite right by one unit\n\
\t\"8\" - Shift sprite up by one unit\n\
\t\"2\" - Shift sprite down by one unit\n\
\t\"+\" - Increase zoom / scale factor\n\
\t\"-\" - Decrease zoom / scale factor\n\
\t\"0\" - Reset sprite display\n\n\
\tUSAGE: ./mhit display PATH_TO_FILE"

// Help Text Variables

const char* helpText = "\n\
\tMHIT Usage Information\n\n\
\tUsage (A mode is *always* supplied ):\n\
\t\tUsage:\t./mhit mode file [file2 ...] [options]\n\n\
\tValid Modes:\n\
\t\thelp\t   --\tDisplays this help message or, if supplied with the name of \
another mode, give specific help for the supplied mode.\n\
\t\tversion\t   --\tGives version and compilation information and exits.\n\
\t\tinfo\t   --\tPrints informtaion from headers/metadata within the supplied \
file.\n\
\t\tcons\t   --\tDraw the image contained within the supplied file.\n\
\t\tconvert\t   --\tCurrently, this mode only converts two specially formatted \
BMP files into a single MHS file.\n\
\t\tvis-test   --\tTests the SDL2-based viewer using one of four tests.\n\
\t\tdisplay\t   --\tDisplays a sprite through SDL2.\n";

const char* hModeTexts[] = {
    INFO_HELP,
    CONS_HELP,
    CONVERT_HELP,
    HELP_TEXT_2,
    VERSION_HELP,
    VIS_TEST_HELP,
    DISPLAY_HELP
};