#include "util.h"

// Variables

const char* invalInfoExt = "Extension not supported. Exiting...\n";

const char* invalDisplayExt = "Passed file is not a sprite file. Exiting...\n";

const int EC_invalExt = 0xBADF11E;

const char* validInfoExts[] = {
    "mhs",
    "bmp"
};

const char* validDisplayExts[] = {
    "mhs"
};

const int valIExtLen = sizeof(validInfoExts) / sizeof(validInfoExts[0]);

const int valDExtLen = sizeof(validDisplayExts) / sizeof(validDisplayExts[0]);

// Functions

void spewInfo(FILE* stream, char* extension){
    int extNum = stringWithinArray(extension, validInfoExts, valIExtLen);
    if(extNum == -1){
        errorOut(invalInfoExt, EC_invalExt);
    }
    switch(extNum){
        case(0):
            pSpr_t* spr = genSpriteObj(stream);
            displaySpriteData(spr);
            destroySpriteObj(spr);
            break;
        case(1):
            bmpRawFile_t* bmp = createRawBMP(stream);
            bmpDetailsOut(bmp);
            destroyRawBMP(bmp);
            break;
        default:
            errorOut(switchDef, EC_switchDef);
    }
}

void spriteDisplay(FILE* stream, char* extension){
    int extNum = stringWithinArray(extension, validDisplayExts, valDExtLen);
    if(extNum == -1){
        errorOut(invalDisplayExt, EC_invalExt);
    }
    switch(extNum){
        case(0):
            int palNum = 0;
            pSpr_t* spr = genSpriteObj(stream);
            printf("Please pick a number between 1 and %d\t-> ",\
                    spr->info->palCount);
            scanf("%d", &palNum);
            palNum--;
            spriteToConsole(spr, palNum);
            destroySpriteObj(spr);
            break;
        default:
            errorOut(switchDef, EC_switchDef);
            break;
    }
}

// Help Text Defines

#define INFO_TEXT "\n\
\tHelp Text for: INFO\n\n\
\"info\" is used to view header information within supported file types.\n\n\
\tUSAGE: ./mhit info PATH_TO_FILE\n\n\
Supported file types are the following:\n\
\tMHS (MH Sprite): A sprite file generated by this program\n\
\tBMP (Bitmap): A Windows bitmap file.\n"

#define DISPLAY_TEXT "\n\
\tHelp Text for: DISPLAY\n\n\
\"display\" is used to draw a generated sprite to the console. This mode can\n\
be used to both quickly view a sprite and check the output from the\n\
\"convert\" mode.\n\n\
\tUSAGE: ./mhit display PATH_TO_FILE\n\n\
Supported file types are the following:\n\
\tMHS (MH Sprite): A sprite file generated by this program\n"

#define CONVERT_TEXT "\n\
\tHelp Text for: CONVERT\n\
\"convert\" is used to create a single MHS file from two specially formatted\n\
BMP files. The \"skeleton\" BMP is a 16-color greyscale image, while the\n\
\"palettes\" image is, at maximum, a 16x16 image, where each row is a palette\n\
in the final sprite. If you decide to save the data, the program will prompt\n\
you for a path relative to the current working directory.\n\n\
\tUSAGE: ./mhit convert PATH_TO_SKELETON PATH_TO_PALETTES\n"

#define HELP_TEXT_2 "\n\
Nice try, very funny; use \"help\" for what you're tying to do.\n"

#define VERSION_INFO "\n\
\tHelp Text for: VERSION\n\n\
\"version\" prints version information and exits. \"Version information\"\n\
includes the following values:\n\
\tProgram Version,\n\
\tGCC version,\n\
\tCompile date and time\n"

// Help Text Variables

const char* helpText = "\n\
\tMHIT Usage Information\n\n\
\tUsage (A mode is *always* supplied ):\n\
\t\tUsage:\t./mhit mode file [file2 ...] [options]\n\n\
\tValid Modes:\n\
\t\thelp\t   --\tDisplays this help message or, if supplied with the name of another \
mode, give specific help for the supplied mode.\n\
\t\tversion\t   --\tGives version and compilation information and exits.\n\
\t\tinfo\t   --\tPrints informtaion from headers/metadata within the supplied file.\n\
\t\tdisplay\t   --\tDraw the image contained within the supplied file.\n\
\t\tconvert\t   --\tCurrently, this mode only converts two specially formatted BMP \
files into a single MHS file.\n";

const char* hModeTexts[] = {
    INFO_TEXT,
    DISPLAY_TEXT,
    CONVERT_TEXT,
    HELP_TEXT_2,
    VERSION_INFO
};